#!/usr/bin/env python3
"""Independent physical-state and interactive first-layer checks (stdlib only).

Run after building: python3 test/first_layer_oracle.py
Optional: --binary /path/to/cube --cases 120

Fixtures use 3D sticker adjacency, balanced flips/twists, and matched cubie
permutation parity. They are not generated by the Go move engine. Interactive
checks simulate the physical moves printed by the CLI; they are not human trials.
"""

import argparse
import collections
import json
from pathlib import Path
import random
import re
import statistics
import subprocess
import threading
import time

FACE_COLORS = "BGORYW"  # Front, Back, Left, Right, Up, Down.
CFEN_ORDER = [4, 3, 0, 5, 2, 1]


def geometry(face, row, col):
    a, b = col - 1, 1 - row
    return [
        ((a, b, 1), (0, 0, 1)), ((-a, b, -1), (0, 0, -1)),
        ((-1, b, a), (-1, 0, 0)), ((1, b, -a), (1, 0, 0)),
        ((a, 1, -b), (0, 1, 0)), ((a, -1, b), (0, -1, 0)),
    ][face]


ADDRESSES = {
    geometry(f, r, c): (f, r, c)
    for f in range(6) for r in range(3) for c in range(3)
}
SOLVED = [[[FACE_COLORS[f]] * 3 for _ in range(3)] for f in range(6)]


def determinant(a, b, c):
    return (a[0] * (b[1] * c[2] - b[2] * c[1])
            - a[1] * (b[0] * c[2] - b[2] * c[0])
            + a[2] * (b[0] * c[1] - b[1] * c[0]))


def physical_pieces():
    groups = collections.defaultdict(list)
    for (position, normal), address in ADDRESSES.items():
        groups[position].append((normal, address))
    edges, corners = [], []
    for _, stickers in sorted(groups.items()):
        if len(stickers) == 2:
            # U/D first, otherwise F/B first, defines edge orientation.
            stickers.sort(key=lambda p: (-abs(p[0][1]), -abs(p[0][2])))
            edges.append([address for _, address in stickers])
        elif len(stickers) == 3:
            # U/D first and consistent outward winding defines corner twists.
            stickers.sort(key=lambda p: -abs(p[0][1]))
            if determinant(*(normal for normal, _ in stickers)) != -1:
                stickers[1], stickers[2] = stickers[2], stickers[1]
            corners.append([address for _, address in stickers])
    assert len(edges) == 12 and len(corners) == 8
    return edges, corners


EDGES, CORNERS = physical_pieces()


def fresh():
    return [[row[:] for row in face] for face in SOLVED]


def color(state, address):
    face, row, col = address
    return state[face][row][col]


def put(state, address, value):
    face, row, col = address
    state[face][row][col] = value


def parity(permutation):
    return sum(permutation[i] > permutation[j]
               for i in range(len(permutation))
               for j in range(i + 1, len(permutation))) % 2


def legal_fixture(rng):
    state = fresh()
    edges, corners = list(range(12)), list(range(8))
    rng.shuffle(edges)
    rng.shuffle(corners)
    if parity(edges) != parity(corners):
        corners[0], corners[1] = corners[1], corners[0]
    flips = [rng.randrange(2) for _ in range(11)]
    flips.append(sum(flips) % 2)
    twists = [rng.randrange(3) for _ in range(7)]
    twists.append(-sum(twists) % 3)
    for slot, piece, flip in zip(EDGES, edges, flips):
        values = [color(SOLVED, address) for address in EDGES[piece]]
        for i, address in enumerate(slot):
            put(state, address, values[i ^ flip])
    for slot, piece, twist in zip(CORNERS, corners, twists):
        values = [color(SOLVED, address) for address in CORNERS[piece]]
        for i, address in enumerate(slot):
            put(state, address, values[(i + twist) % 3])
    return state


def quarter_turn(vector, axis):
    x, y, z = vector
    return [(x, z, -y), (-z, y, x), (y, -x, z)][axis]


def physical_move(state, token):
    turns = 2 if token.endswith("2") else 3 if token.endswith("'") else 1
    base = token.rstrip("'2")
    sides = {"R": (0, 1), "L": (0, -1), "U": (1, 1),
             "D": (1, -1), "F": (2, 1), "B": (2, -1)}
    if base in ["x", "y", "z"]:
        axis = "xyz".index(base)
        selected = lambda position: True
    elif base in ["M", "E", "S"]:
        axis, sign = {"M": (0, -1), "E": (1, -1), "S": (2, 1)}[base]
        turns = sign * turns % 4
        selected = lambda position: position[axis] == 0
    else:
        axis, sign = sides[base[0]]
        turns = sign * turns % 4
        threshold = 0 if base.endswith("w") else 1
        selected = lambda position: sign * position[axis] >= threshold
    after = fresh()
    for (position, normal), address in ADDRESSES.items():
        if selected(position):
            for _ in range(turns):
                position = quarter_turn(position, axis)
                normal = quarter_turn(normal, axis)
        put(after, ADDRESSES[position, normal], color(state, address))
    return after


def physical_sequence(state, sequence):
    for token in sequence.split():
        state = physical_move(state, token)
    return state


def cfen(state):
    return "YB|" + "/".join(
        "".join(color(state, (face, row, col))
                for row in range(3) for col in range(3))
        for face in CFEN_ORDER)


def decode(text):
    fields = text.strip().split("|")[1].split("/")
    assert len(fields) == 6, text
    state = fresh()
    for face, field in zip(CFEN_ORDER, fields):
        tokens = re.findall(r"([WYROGB])([0-9]*)", field)
        assert "".join(value + count for value, count in tokens) == field, text
        stickers = "".join(value * int(count or 1) for value, count in tokens)
        assert len(stickers) == 9, text
        for index, value in enumerate(stickers):
            put(state, (face, index // 3, index % 3), value)
    return state


def white_layer(state):
    return (all(value == "W" for row in state[5] for value in row)
            and all(state[face][2][col] == state[face][1][1]
                    for face in range(4) for col in range(3)))


def orientation_paths():
    queue, seen = [(fresh(), "")], {cfen(fresh())}
    for state, path in queue:
        for axis in ["x", "y", "z"]:
            after = physical_move(state, axis)
            key = cfen(after)
            if key not in seen:
                seen.add(key)
                queue.append((after, path + " " + axis))
    assert len(queue) == 24
    return [path for _, path in queue]


def run(binary, args, text=None):
    if args[0] == "learn" and "--goal" not in args:
        args = args + ["--goal", "first-layer"]
    return subprocess.run([str(binary)] + args, input=text, text=True,
                          capture_output=True, timeout=3)


def displayed_states(output):
    return [decode(state) for state in re.findall(
        r"(?:Saved state: |learn> )(YB\|[^\n]+)", output)]


def check_fixtures(binary, count):
    rng, durations, paths = random.Random(60913), [], orientation_paths()
    for index in range(count):
        state = physical_sequence(legal_fixture(rng), paths[index % 24])
        started = time.perf_counter()
        result = run(binary, ["solve", "", "--goal", "first-layer", "--start",
                              cfen(state), "--cfen"])
        durations.append(time.perf_counter() - started)
        assert result.returncode == 0, (index, result.stderr)
        assert white_layer(decode(result.stdout)), (index, result.stdout)
    rejected = {}
    for kind in ["edge_flip", "corner_twist", "parity", "mirror"]:
        state = fresh()
        if kind == "edge_flip":
            a, b = EDGES[0]
            va, vb = color(state, a), color(state, b)
            put(state, a, vb)
            put(state, b, va)
        elif kind == "corner_twist":
            group = CORNERS[0]
            values = [color(state, address) for address in group]
            for i, address in enumerate(group):
                put(state, address, values[(i + 1) % 3])
        elif kind == "mirror":
            a, b = CORNERS[0][1:]
            va, vb = color(state, a), color(state, b)
            put(state, a, vb)
            put(state, b, va)
        else:
            a, b = CORNERS[:2]
            va = [color(state, address) for address in a]
            vb = [color(state, address) for address in b]
            for address, value in zip(a, vb):
                put(state, address, value)
            for address, value in zip(b, va):
                put(state, address, value)
        result = run(binary, ["solve", "", "--goal", "first-layer", "--start",
                              cfen(state), "--cfen"])
        assert result.returncode != 0 and not result.stdout, (kind, result.stdout)
        expected = {"edge_flip": "flipped edges", "corner_twist": "corner twists",
                    "parity": "parity", "mirror": "mirrored"}[kind]
        assert expected in result.stderr, (kind, result.stderr)
        rejected[kind] = "rejected"
    return {"legal_cubie_states": count, "orientations": min(count, 24),
            "impossible_cubie_states": rejected,
            "process_latency_ms": {
                "median": round(statistics.median(durations) * 1000, 2),
                "max": round(max(durations) * 1000, 2)}}


def check_invalid_arguments(binary):
    invalid = [
        ["learn", "R3"], ["learn", "4R"], ["learn", "R", "--dimension", "4"],
        ["learn", "--start", "YB|Y999999999/R9/B9/W9/O9/G9"],
        ["learn", "--start", "YB|Y9/R9/B9/W9/O9/?9"],
        ["learn", "--start", "YB|Y4/R4/B4/W4/O4/G4"],
        ["learn", "--start", "YB|Y9/R9/B9/W9/O9/G8"],
        ["solve", "R", "--goal", "first-layer", "--algorithm", "cfop"],
        ["learn", "R " * 5000],
    ]
    for args in invalid:
        result = run(binary, args)
        assert result.returncode != 0 and not result.stdout, (args, result.stdout)
        assert result.stderr.count("Error:") == 1, result.stderr
    return len(invalid)


def check_numbered_turns(binary):
    equivalents = {"2R": "M'", "2L": "M", "2U": "E'",
                   "2D": "E", "2F": "S", "2B": "S'"}
    checked = 0
    for numbered, equivalent in equivalents.items():
        for suffix in ["", "'", "2"]:
            turn = numbered + suffix
            physical_turn = equivalent
            if suffix == "'":
                physical_turn = (equivalent[:-1] if equivalent.endswith("'")
                                 else equivalent + "'")
            elif suffix == "2":
                physical_turn = equivalent.rstrip("'") + "2"
            initial = physical_move(fresh(), physical_turn)
            result = run(binary, ["twist", turn, "--cfen"])
            assert result.returncode == 0, result.stderr
            assert decode(result.stdout) == initial, turn
            for goal in ["first-layer", "full"]:
                result = run(binary, ["solve", turn, "--goal", goal, "--headless"])
                assert result.returncode == 0, result.stderr
                replay = physical_sequence(initial, result.stdout)
                if goal == "first-layer":
                    assert white_layer(replay), turn
                else:
                    assert all(value == face[1][1] for face in replay
                               for row in face for value in row), turn
            result = run(binary, ["learn", turn])
            assert result.returncode == 0, result.stderr
            moves = re.search(r"^First-layer moves: (.*)$", result.stdout, re.M)
            assert moves, result.stdout
            replay = physical_sequence(initial, moves.group(1))
            assert white_layer(replay) and displayed_states(result.stdout) == [replay], turn
            checked += 1
    return checked


def check_scripted_sessions(binary):
    initial = physical_sequence(fresh(), "R U F2 L B")
    actual = "R U x y'"
    text = ("hint\nshow\nstate\nmoves " + actual
            + "\nstate\nundo\nstate\nmoves F2 D'\nreset\nstate"
            + "\nnext\nstate\nundo\nstate\nquit\n")
    result = run(binary, ["learn", "R U F2 L B", "--interactive"], text)
    assert result.returncode == 0, result.stderr
    states = displayed_states(result.stdout)
    assert states[:4] == [initial] * 4
    assert states[4:6] == [physical_sequence(initial, actual)] * 2
    assert states[6:8] == [initial] * 2 and states[-1] == initial
    assert "Undo on your physical cube:" in result.stdout
    assert "Reset on your physical cube:" in result.stdout
    for text in ["nonsense\nstate\nquit\n", "moves R bad U\nstate\nquit\n",
                 "undo\nundo\nreset\nstate\nquit\n"]:
        result = run(binary, ["learn", "R", "--interactive"], text)
        assert result.returncode == 0, result.stderr
        assert all(state == physical_move(fresh(), "R")
                   for state in displayed_states(result.stdout))
    result = run(binary, ["learn", "U", "--interactive"],
                 "next\nnext\nnext\nquit\n")
    assert result.returncode == 0 and result.stdout.count("no moves applied") == 3
    result = run(binary, ["learn", "R", "--interactive"],
                 "moves " + "R " * 5000 + "\nstate\nquit\n")
    assert result.returncode == 0 and "No state changed" in result.stdout
    assert all(state == physical_move(fresh(), "R")
               for state in displayed_states(result.stdout))
    assert "Resume:" in result.stdout, result.stdout
    result = run(binary, ["learn", "R", "--interactive"], "")
    assert result.returncode == 0 and "Input ended. Resume:" in result.stdout
    return 7  # One history script, three invalid/repeated scripts, completion, size, EOF.


def read_prompt(process):
    output = ""
    while not output.endswith("learn> "):
        character = process.stdout.read(1)
        assert character, "Unexpected process exit: " + output
        output += character
        assert len(output) < 100000, "Unexpectedly large lesson output"
    return output


def checked_command(process, command, physical_state, inverse_label=None):
    process.stdin.write(command + "\n")
    process.stdin.flush()
    output = read_prompt(process)
    if inverse_label:
        match = re.search(inverse_label + r": ([^\n]*)", output)
        assert match, output
        physical_state = physical_sequence(physical_state, match.group(1))
    match = re.search(r"Saved state: (YB\|[^\n]+)", output)
    assert match and decode(match.group(1)) == physical_state, (command, output)
    return output, physical_state


def check_live_sessions(binary):
    cases = []
    for scramble in ["R U F2 L B", "x y' R2 B' F U2 D"]:
        state = physical_sequence(fresh(), scramble)
        cases.append((["learn", scramble, "--interactive"], state))
    state = physical_sequence(legal_fixture(random.Random(1231)), "z x2")
    cases.append((["learn", "--start", cfen(state), "--interactive"], state))
    counts = []
    for args, initial in cases:
        args = args + ["--goal", "first-layer"]
        process = subprocess.Popen([str(binary)] + args, stdin=subprocess.PIPE,
                                   stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                   text=True)
        # Bound the entire conversation, including reads of prompts without
        # newlines, so a CLI regression cannot leave this test hanging.
        deadline = threading.Timer(5, process.kill)
        deadline.daemon = True
        deadline.start()
        try:
            state, output = initial, read_prompt(process)
            match = re.search(r"Saved state: (YB\|[^\n]+)", output)
            assert match and decode(match.group(1)) == state
            moves = " ".join(re.findall(r"  Do: ([^\n]+)", output))
            assert moves, output
            state = physical_sequence(state, moves)
            output, state = checked_command(process, "next", state)
            output, state = checked_command(process, "undo", state,
                                            "Undo on your physical cube")
            assert state == initial
            state = physical_sequence(state, "R U x'")
            output, state = checked_command(process, "moves R U x'", state)
            output, state = checked_command(process, "reset", state,
                                            "Reset on your physical cube")
            assert state == initial
            checkpoints = 0
            while "Next checkpoint:" in output:
                moves = " ".join(re.findall(r"  Do: ([^\n]+)", output))
                assert moves, output
                state = physical_sequence(state, moves)
                output, state = checked_command(process, "next", state)
                checkpoints += 1
                assert checkpoints < 15
            assert white_layer(state)
            output, state = checked_command(process, "next", state)
            assert "no moves applied" in output
            output, state = checked_command(process, "reset", state,
                                            "Reset on your physical cube")
            assert state == initial
            process.stdin.write("quit\n")
            process.stdin.flush()
            process.communicate(timeout=3)
            assert process.returncode == 0
            counts.append(checkpoints)
        finally:
            deadline.cancel()
            if process.poll() is None:
                process.kill()
                process.communicate()
    return counts


def check_rotated_wording(binary):
    result = run(binary, ["learn", "x", "--interactive"], "next\nquit\n")
    assert result.returncode == 0, result.stderr
    assert "Start in the orientation represented by the input state" in result.stdout
    initial, after = result.stdout.split("learn> Confirmed:", 1)
    assert "all four side bottom rows" not in initial, initial
    assert "all four side bottom rows" in after, after
    assert "Next checkpoint: Hold white down" in initial
    return 1


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--binary", type=Path,
                        default=Path(__file__).resolve().parents[1] / "dist" / "cube")
    parser.add_argument("--cases", type=int, default=120)
    args = parser.parse_args()
    if args.cases < 1:
        parser.error("--cases must be positive")
    binary = args.binary.resolve()
    if not binary.is_file():
        parser.error("Cube binary missing; run make build or pass --binary")
    result = check_fixtures(binary, args.cases)
    result["invalid_argument_cases"] = check_invalid_arguments(binary)
    result["numbered_turn_physical_replays"] = check_numbered_turns(binary)
    result["scripted_interactive_sessions"] = check_scripted_sessions(binary)
    result["live_session_checkpoint_counts"] = check_live_sessions(binary)
    result["rotated_instruction_check"] = check_rotated_wording(binary)
    result["ux_evidence"] = "Independent simulated physical moves; no human physical trial"
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
