package cube

import (
	_ "embed"
	"encoding/json"
	"strings"
)

// UpdateMoveCount calculates and updates the move count for an algorithm
func (a *Algorithm) UpdateMoveCount() error {
	moves, err := ParseScramble(a.Moves)
	if err != nil {
		return err
	}
	a.MoveCount = len(moves)
	return nil
}

// Algorithm represents a named cube algorithm with pattern-based verification
type Algorithm struct {
	// Core Identity
	Name       string   // e.g., "Sune"
	CaseID     string   // e.g., "OLL-27" (standardized format)
	Category   string   // OLL, PLL, F2L, Trigger, etc.
	Categories []string // All categories represented by merged duplicates.
	Dimension  int      // Cube size; generated records always set this explicitly.
	Sources    []string // CSV file:row provenance, or builtin.
	References []string
	Aliases    []string // Names/IDs merged from duplicate rows.
	InverseID  string   // Automatically detected exact inverse effect.

	// Algorithm Definition
	Moves     string // e.g., "R U R' U R U2 R'"
	MoveCount int    // Auto-calculated from Moves

	// Pattern Representation - NEW APPROACH
	Pattern string // Concrete inverse-to-solved CFEN recognition state

	// Human-Friendly Info
	Description string // What this algorithm does
	Recognition string // How to recognize when to use it

	// Optional Metadata
	Probability float64  // Chance of occurring in solve
	Variants    []string // Alternative move sequences
	Inverse     string   // Inverse algorithm (if meaningful)

	// Relationships
	Mirror  string   // ID of mirror algorithm (e.g., "OLL-26" for Sune)
	Related []string // IDs of related algorithms
}

//go:embed algorithms_data.json
var algorithmData []byte

// AlgorithmDatabase is generated by tools/import-algorithms. Patterns are
// concrete recognition states: applying Moves to Pattern produces solved.
var AlgorithmDatabase = func() []Algorithm {
	var db []Algorithm
	if err := json.Unmarshal(algorithmData, &db); err != nil {
		panic(err)
	}
	return db
}()

// LookupAlgorithm searches for algorithms by name or moves
func LookupAlgorithm(query string) []Algorithm {
	query = strings.ToLower(strings.TrimSpace(query))
	var results []Algorithm

	for _, alg := range AlgorithmDatabase {
		// Check if query matches name, moves, or description
		if strings.Contains(strings.ToLower(alg.Name), query) ||
			strings.Contains(strings.ToLower(alg.Moves), query) ||
			strings.Contains(strings.ToLower(alg.Description), query) ||
			strings.Contains(strings.ToLower(alg.CaseID), query) ||
			matchesAlias(alg.Aliases, query) {
			results = append(results, alg)
		}
	}

	return results
}

// LookupByMoves finds algorithms that exactly match the given moves
func LookupByMoves(moves string) []Algorithm {
	moves = strings.TrimSpace(moves)
	var results []Algorithm

	for _, alg := range AlgorithmDatabase {
		if alg.Moves == moves {
			results = append(results, alg)
		}
	}

	return results
}

// GetByCategory returns all algorithms in a given category
func GetByCategory(category string) []Algorithm {
	category = strings.ToUpper(strings.TrimSpace(category))
	var results []Algorithm

	for _, alg := range AlgorithmDatabase {
		if alg.HasCategory(category) {
			results = append(results, alg)
		}
	}

	return results
}

// CalculateMoveCount returns the number of moves in an algorithm string
func (alg *Algorithm) CalculateMoveCount() int {
	if alg.Moves == "" {
		return 0
	}

	moves, err := ParseScramble(alg.Moves)
	if err != nil {
		return 0
	}

	return len(moves)
}

func matchesAlias(aliases []string, query string) bool {
	for _, alias := range aliases {
		if strings.Contains(strings.ToLower(alias), query) {
			return true
		}
	}
	return false
}

func (alg Algorithm) HasCategory(category string) bool {
	if strings.EqualFold(alg.Category, category) {
		return true
	}
	for _, stored := range alg.Categories {
		if strings.EqualFold(stored, category) {
			return true
		}
	}
	return false
}
